import os
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken
from dotenv import load_dotenv

load_dotenv((Path(__file__).resolve().parent / ".env").resolve(), override=True)


def _get_master_key() -> bytes:
    """
    Resolve and validate the MASTER_KEY from the environment.

    Expects MASTER_KEY to be a valid Fernet key (URL-safe base64-encoded 32 bytes).
    You can generate one with:

        from cryptography.fernet import Fernet
        print(Fernet.generate_key().decode())
    """
    key = os.getenv("MASTER_KEY")
    if not key:
        raise EnvironmentError(
            "MASTER_KEY is not set. Please define a valid Fernet key in your .env file."
        )

    try:
        # Fernet will validate the key format when instantiated.
        Fernet(key.encode())
    except (ValueError, TypeError) as exc:
        raise EnvironmentError(
            "MASTER_KEY is invalid. It must be a URL-safe base64-encoded 32-byte key "
            "generated by cryptography.fernet.Fernet.generate_key()."
        ) from exc

    return key.encode()


MASTER_KEY: bytes = _get_master_key()
fernet = Fernet(MASTER_KEY)


def encrypt_data(plain_text: str) -> str:
    """
    Encrypt a string and return the ciphertext as a UTF-8 string.
    """
    if plain_text is None:
        raise ValueError("plain_text must not be None.")
    token = fernet.encrypt(plain_text.encode("utf-8"))
    return token.decode("utf-8")


def decrypt_data(encrypted_text: str) -> str:
    """
    Decrypt a previously encrypted string and return the original plaintext.
    """
    if encrypted_text is None:
        raise ValueError("encrypted_text must not be None.")
    try:
        decrypted = fernet.decrypt(encrypted_text.encode("utf-8"))
    except InvalidToken as exc:
        raise ValueError("Failed to decrypt data. The token may be invalid or corrupted.") from exc
    return decrypted.decode("utf-8")


if __name__ == "__main__":
    test_value = "binance_secret_123"
    print(f"Original: {test_value}")

    encrypted = encrypt_data(test_value)
    print(f"Encrypted: {encrypted}")

    decrypted = decrypt_data(encrypted)
    print(f"Decrypted: {decrypted}")